[alembic]
script_location = %(here)s/migrations
sqlalchemy.url = postgresql://postgres:postgres@localhost:5433/platform

[post_write_hooks]
hooks = create_sql_files
create_sql_files.type = exec
create_sql_files.executable = python3
create_sql_files.options = %(here)s/scripts/create_sql_files.py REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
